let firstNum: Number;
let SecondNum: Number;
let thirdNum : Number;
let FourthNum : Number;
firstNum = 4+4;
SecondNum=10-2;
thirdNum=2*4;
FourthNum=80/10;
console.log("firstNum = 4+4; "+firstNum);
console.log("SecondNum=10-2; "+SecondNum);
console.log("thirdNum=2*4; "+thirdNum);
console.log("FourthNum=80/10; "+FourthNum);